# Generated by Django 4.2.17 on 2025-05-29 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('inn', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='ИНН')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Организацию',
                'verbose_name_plural': 'Организации',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID операции')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('payer_inn', models.CharField(max_length=12, verbose_name='ИНН организации')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('document_date', models.DateTimeField(verbose_name='Дата документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
                'ordering': ('payer_inn', '-created_at'),
            },
        ),
    ]
